//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WindowsFormsApplication1.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE documentElement[
        ///&lt;!ENTITY nbsp    &quot;&amp;#160;&quot; &gt;
        ///&lt;!ENTITY iexcl   &quot;&amp;#161;&quot; &gt;
        ///&lt;!ENTITY cent    &quot;&amp;#162;&quot; &gt;
        ///&lt;!ENTITY pound   &quot;&amp;#163;&quot; &gt;
        ///&lt;!ENTITY curren  &quot;&amp;#164;&quot; &gt;
        ///&lt;!ENTITY yen     &quot;&amp;#165;&quot; &gt;
        ///&lt;!ENTITY brvbar  &quot;&amp;#166;&quot; &gt;
        ///&lt;!ENTITY sect    &quot;&amp;#167;&quot; &gt;
        ///&lt;!ENTITY uml     &quot;&amp;#168;&quot; &gt;
        ///&lt;!ENTITY copy    &quot;&amp;#169;&quot; &gt;
        ///&lt;!ENTITY ordf    &quot;&amp;#170;&quot; &gt;
        ///&lt;!ENTITY laquo   &quot;&amp;#171;&quot; &gt;
        ///&lt;!ENTITY not     &quot;&amp;#172;&quot; &gt;
        ///&lt;!ENTITY shy     &quot;&amp;#173;&quot; &gt;
        ///&lt;!ENTITY reg     &quot;&amp;#174;&quot; &gt;
        ///&lt;!ENTITY macr    &quot;&amp;#175;&quot; &gt;
        ///&lt;!ENTITY deg     &quot;&amp;# [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string entity_def {
            get {
                return ResourceManager.GetString("entity_def", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;xsl:stylesheet version=&quot;2.0&quot; 
        ///xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot;&gt;
        ///&lt;xsl:output method=&quot;xml&quot; version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; indent=&quot;yes&quot;/&gt;
        ///&lt;xsl:strip-space elements=&quot;*&quot;/&gt;
        ///
        ///&lt;xsl:template match=&quot;*&quot;&gt;
        ///    &lt;xsl:element name=&quot;{lower-case(local-name())}&quot; namespace=&quot;{namespace-uri()}&quot;&gt;
        ///        &lt;xsl:apply-templates select=&quot;@*|node()&quot;/&gt;
        ///    &lt;/xsl:element&gt;
        ///&lt;/xsl:template&gt;
        ///
        ///&lt;xsl:template match=&quot;@*&quot;&gt;
        ///    &lt;xsl:attribute name=&quot;{lower-case(local-name())}&quot; namespace=&quot;{namespace-uri()}&quot;&gt;
        ///        &lt;xs [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string lowercase_xslt {
            get {
                return ResourceManager.GetString("lowercase_xslt", resourceCulture);
            }
        }
    }
}
